server:
  port: 8080
  max-http-request-header-size: 200MB

spring:
  mail:
    host: smtp.163.com
    port: 465
    username: maojas@163.com
    password: UZysiH7AesagkGzt
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
          ssl:
            enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/you_cun?useSSL=false&serverTimezone=UTC
    username: you_cun
    password: mw200464

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false

